### ISSUE TITLE
Typo in parameters() function description

### ISSUE THREAD

**Issue by alexee-mayette** [dankelley/whalestrike#25]
On the reference page for the [parameters()](https://dankelley.github.io/whalestrike/reference/parameters.html) function, there is a typo in the description of the Ss argument.

**Ss**: This, together with Cs, is used by **_used by_** [shipWaterForce()](https://dankelley.github.io/whalestrike/reference/shipWaterForce.html) to estimate ship drag force.

**Comment by dankelley** [comment]
I'm closing, since this was done a few months ago. Thanks!
