### ISSUE TITLE
whaleAreaFromLength() does not work with other whale species

### ISSUE THREAD

**Issue by alexee-mayette** [dankelley/whalestrike#27]
The function whaleAreaFromLength() does not work when using other species than "N. Atl. Right Whale".

```
whaleAreaFromLength(13.7, "Blue Whale", type = "wetted")

Error in whaleAreaFromLength(13.7, "Blue Whale", type = "wetted") : 
  unknown species "Blue Whale"; use one of the following: "N. Atl. Right Whale"
```

**Comment by dankelley** [comment]
This issue has been addressed in the "main" branch of 
 https://github.com/dankelley/whalestrike 
in commit  98701aa997784dfe99fd92908c9a466464f5eb82, by altering the function description to let users know that the package only handles one species, in this version.

**Comment by dankelley** [comment]
I'm closing, since this was handled (partially -- just by being clearer)  a few months ago. Thanks!
